### ISSUE TITLE
Build hangs when dockerHost is in tcp protocol

### ISSUE THREAD

**Issue by Manuri** [ballerinax/kubernetes#269]
**Description:**
```ballerina
@kubernetes:Deployment {
    image: "ballerina.guides.io/employee_database_service:v1.0",
    name: "ballerina-guides-employee-database-service",
    baseImage: "ballerina/ballerina:0.990.3",
    copyFiles: [{ target: "/ballerina/runtime/bre/lib",
                source: "/path/to/mysql-connector-java-5.1.46.jar"}]//
    dockerHost: "tcp://192.168.99.100:2376", // minikube docker host
    dockerCertPath: "/home/manurip/.minikube"
}
```

When running

```bash
ballerina build data_backed_service
```

build hangs at

```bash
Compiling source
    manurip/data_backed_service:0.0.1

Generating executable
    ./target/data_backed_service.balx
	@kubernetes:Service 			 - complete 1/1
	@kubernetes:Ingress 			 - complete 1/1
	@kubernetes:Deployment 			 - complete 1/1
	@kubernetes:Docker 			 - complete 1/3 
```

When debugging with ballerinax/docker source, observed the following exception
```bash
com.spotify.docker.client.exceptions.DockerException: java.util.concurrent.ExecutionException: javax.ws.rs.ProcessingException: org.apache.http.conn.UnsupportedSchemeException: tcp protocol is not supported
	at com.spotify.docker.client.DefaultDockerClient.propagate(DefaultDockerClient.java:2843)
	at com.spotify.docker.client.DefaultDockerClient.request(DefaultDockerClient.java:2707)
	at com.spotify.docker.client.DefaultDockerClient.version(DefaultDockerClient.java:595)
	at com.spotify.docker.client.DefaultDockerClient.authRegistryHeader(DefaultDockerClient.java:2886)
	at com.spotify.docker.client.DefaultDockerClient.build(DefaultDockerClient.java:1493)
	at com.spotify.docker.client.DefaultDockerClient.build(DefaultDockerClient.java:1460)
	at org.ballerinax.docker.generator.DockerArtifactHandler.buildImage(DockerArtifactHandler.java:111)
	at org.ballerinax.docker.generator.DockerArtifactHandler.createArtifacts(DockerArtifactHandler.java:81)
	at org.ballerinax.kubernetes.handlers.DockerHandler.createArtifacts(DockerHandler.java:47)
	at org.ballerinax.kubernetes.ArtifactManager.createArtifacts(ArtifactManager.java:80)
	at org.ballerinax.kubernetes.KubernetesPlugin.codeGenerated(KubernetesPlugin.java:141)
	at org.wso2.ballerinalang.compiler.BinaryFileWriter.lambda$writeExecutableBinary$0(BinaryFileWriter.java:121)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at org.wso2.ballerinalang.compiler.BinaryFileWriter.writeExecutableBinary(BinaryFileWriter.java:120)
	at org.wso2.ballerinalang.compiler.BinaryFileWriter.write(BinaryFileWriter.java:95)
	at org.wso2.ballerinalang.compiler.Compiler.write(Compiler.java:117)
	at org.ballerinalang.packerina.BuilderUtils.compileWithTestsAndWrite(BuilderUtils.java:78)
	at org.ballerinalang.packerina.cmd.BuildCommand.execute(BuildCommand.java:177)
	at java.util.Optional.ifPresent(Optional.java:159)
	at org.ballerinalang.launcher.Main.main(Main.java:67)
Caused by: java.util.concurrent.ExecutionException: javax.ws.rs.ProcessingException: org.apache.http.conn.UnsupportedSchemeException: tcp protocol is not supported
	at jersey.repackaged.com.google.common.util.concurrent.AbstractFuture$Sync.getValue(AbstractFuture.java:299)
	at jersey.repackaged.com.google.common.util.concurrent.AbstractFuture$Sync.get(AbstractFuture.java:286)
	at jersey.repackaged.com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:116)
	at com.spotify.docker.client.DefaultDockerClient.request(DefaultDockerClient.java:2705)
	... 18 more
Caused by: javax.ws.rs.ProcessingException: org.apache.http.conn.UnsupportedSchemeException: tcp protocol is not supported
	at org.glassfish.jersey.apache.connector.ApacheConnector.apply(ApacheConnector.java:481)
	at org.glassfish.jersey.apache.connector.ApacheConnector$1.run(ApacheConnector.java:491)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at jersey.repackaged.com.google.common.util.concurrent.MoreExecutors$DirectExecutorService.execute(MoreExecutors.java:299)
	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:112)
	at jersey.repackaged.com.google.common.util.concurrent.AbstractListeningExecutorService.submit(AbstractListeningExecutorService.java:50)
	at jersey.repackaged.com.google.common.util.concurrent.AbstractListeningExecutorService.submit(AbstractListeningExecutorService.java:37)
	at org.glassfish.jersey.apache.connector.ApacheConnector.apply(ApacheConnector.java:487)
	at org.glassfish.jersey.client.ClientRuntime$2.run(ClientRuntime.java:178)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:340)
	at org.glassfish.jersey.client.ClientRuntime$3.run(ClientRuntime.java:210)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.http.conn.UnsupportedSchemeException: tcp protocol is not supported
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:108)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:71)
	at org.glassfish.jersey.apache.connector.ApacheConnector.apply(ApacheConnector.java:435)
	... 21 more
```

Looks like tcp protocol is not supported with new docker client. Found the following related issue in spotify client.
https://github.com/spotify/docker-client/issues/946

**Comment by Manuri** [comment]
Fixed with https://github.com/ballerinax/docker/pull/186
