### ISSUE TITLE
Kubernetes artifacts are not generated without @kubernetes:Service annotation

### ISSUE THREAD

**Issue by boxidilshan** [ballerinax/kubernetes#433]
**Description:**
I could get the Kubernetes samples working without any issues. I tried to create Kubernetes artifacts for a usecase which has a FTP listener. Ideally for such use cases only deployment artifacts will exist and services will not be applicable. This is the only Kubernetes annotation which we will require in such cases in my opinion. 

@kubernetes:Deployment {
    livenessProbe: true,
    image: "ftplistenertest:v.1.0",
    dockerHost: "tcp://192.168.64.3:2376",
    dockerCertPath: "/Users/dilshan/.minikube/certs"
}

When I create this with above annotation I get following error.

Compiling source
	dilshan/ftptest:0.1.0

Creating balos
	target/balo/ftptest-2019r3-any-0.1.0.balo

Generating executables
	target/bin/ftptest.jar

Generating artifacts...
ballerina: Oh no, something really went wrong. Bad. Sad.

There should be a file named "ballerina-internal.log" in the current directory.
If you are able to share with us the code that broke Ballerina then
we would REALLY appreciate if you would report this to us:
go to https://github.com/ballerina-platform/ballerina-lang/issues and
create a bug report with both this log file and the sample code.

This is the error available in ballerina-internal.log

[2019-12-10 18:41:38,426] SEVERE {b7a.log.crash} - null 
java.util.NoSuchElementException
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1447)
	at java.util.HashMap$KeyIterator.next(HashMap.java:1469)
	at org.ballerinax.kubernetes.handlers.DeploymentHandler.createArtifacts(DeploymentHandler.java:313)
	at org.ballerinax.kubernetes.ArtifactManager.createArtifacts(ArtifactManager.java:84)
	at org.ballerinax.kubernetes.KubernetesPlugin.codeGenerated(KubernetesPlugin.java:164)
	at org.ballerinalang.packerina.task.RunCompilerPluginTask.lambda$execute$0(RunCompilerPluginTask.java:36)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at org.ballerinalang.packerina.task.RunCompilerPluginTask.execute(RunCompilerPluginTask.java:35)
	at org.ballerinalang.packerina.TaskExecutor.executeTasks(TaskExecutor.java:38)
	at org.ballerinalang.packerina.cmd.BuildCommand.execute(BuildCommand.java:395)
	at java.util.Optional.ifPresent(Optional.java:159)
	at org.ballerinalang.tool.Main.main(Main.java:59)
 

As a workaround I tried to add a dummy http service and got this to work.  

**Suggested Labels:**
kubernetes, ballerina

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by anuruddhal** [comment]
@boxidilshan You can add Deployment annotation without `livenessProbe: true` attribute. The error occurs when trying to detect the port for the liveness probe. 

AFAIU there should be a service created for your scenario as you are trying to implement an FTP listener. Can you explain why the @kubernetes: Service annotation shouldn't be added to the listener?

```Ballerina
@kubernetes:Deployment {
image: "ftplistenertest:v.1.0",
dockerHost: "tcp://192.168.64.3:2376",
dockerCertPath: "/Users/dilshan/.minikube/certs"
}
```
